DROP DATABASE IF EXISTS battles;

CREATE DATABASE battles;

USE battles;

DROP TABLE IF EXISTS battles_data;

CREATE TABLE battles_data(
   name               VARCHAR(100) NOT NULL PRIMARY KEY
  ,year               INTEGER  
  ,battle_number      INTEGER  
  ,attacker_king      VARCHAR(50)
  ,defender_king      VARCHAR(50)
  ,attacker_1         VARCHAR(50) 
  ,attacker_2         VARCHAR(50)
  ,attacker_3         VARCHAR(50)
  ,attacker_4         VARCHAR(50)
  ,defender_1         VARCHAR(50)
  ,defender_2         VARCHAR(50)
  ,defender_3         VARCHAR(50)
  ,defender_4         VARCHAR(50)
  ,attacker_outcome   VARCHAR(4)
  ,battle_type        VARCHAR(50)
  ,major_death        BIT 
  ,major_capture      BIT 
  ,attacker_size      INTEGER 
  ,defender_size      INTEGER 
  ,attacker_commander VARCHAR(1000)
  ,defender_commander VARCHAR(1000)
  ,summer             BIT 
  ,location           VARCHAR(50)
  ,region             VARCHAR(50) 
  ,note               VARCHAR(1000)
);
INSERT INTO battles_data(name,year,battle_number,attacker_king,defender_king,attacker_1,attacker_2,attacker_3,attacker_4,defender_1,defender_2,defender_3,defender_4,attacker_outcome,battle_type,major_death,major_capture,attacker_size,defender_size,attacker_commander,defender_commander,summer,location,region,note) VALUES ('Battle of the Golden Tooth',298,1,'Joffrey/Tommen Baratheon','Robb Stark','Lannister',NULL,NULL,NULL,'Tully',NULL,NULL,NULL,'win','pitched battle',1,0,15000,4000,'Jaime Lannister','Clement Piper, Vance',1,'Golden Tooth','The Westerlands',NULL);
INSERT INTO battles_data(name,year,battle_number,attacker_king,defender_king,attacker_1,attacker_2,attacker_3,attacker_4,defender_1,defender_2,defender_3,defender_4,attacker_outcome,battle_type,major_death,major_capture,attacker_size,defender_size,attacker_commander,defender_commander,summer,location,region,note) VALUES ('Battle at the Mummer''s Ford',298,2,'Joffrey/Tommen Baratheon','Robb Stark','Lannister',NULL,NULL,NULL,'Baratheon',NULL,NULL,NULL,'win','ambush',1,0,NULL,120,'Gregor Clegane','Beric Dondarrion',1,'Mummer''s Ford','The Riverlands',NULL);
INSERT INTO battles_data(name,year,battle_number,attacker_king,defender_king,attacker_1,attacker_2,attacker_3,attacker_4,defender_1,defender_2,defender_3,defender_4,attacker_outcome,battle_type,major_death,major_capture,attacker_size,defender_size,attacker_commander,defender_commander,summer,location,region,note) VALUES ('Battle of Riverrun',298,3,'Joffrey/Tommen Baratheon','Robb Stark','Lannister',NULL,NULL,NULL,'Tully',NULL,NULL,NULL,'win','pitched battle',0,1,15000,10000,'Jaime Lannister, Andros Brax','Edmure Tully, Tytos Blackwood',1,'Riverrun','The Riverlands',NULL);
INSERT INTO battles_data(name,year,battle_number,attacker_king,defender_king,attacker_1,attacker_2,attacker_3,attacker_4,defender_1,defender_2,defender_3,defender_4,attacker_outcome,battle_type,major_death,major_capture,attacker_size,defender_size,attacker_commander,defender_commander,summer,location,region,note) VALUES ('Battle of the Green Fork',298,4,'Robb Stark','Joffrey/Tommen Baratheon','Stark',NULL,NULL,NULL,'Lannister',NULL,NULL,NULL,'loss','pitched battle',1,1,18000,20000,'Roose Bolton, Wylis Manderly, Medger Cerwyn, Harrion Karstark, Halys Hornwood','Tywin Lannister, Gregor Clegane, Kevan Lannister, Addam Marbrand',1,'Green Fork','The Riverlands',NULL);
INSERT INTO battles_data(name,year,battle_number,attacker_king,defender_king,attacker_1,attacker_2,attacker_3,attacker_4,defender_1,defender_2,defender_3,defender_4,attacker_outcome,battle_type,major_death,major_capture,attacker_size,defender_size,attacker_commander,defender_commander,summer,location,region,note) VALUES ('Battle of the Whispering Wood',298,5,'Robb Stark','Joffrey/Tommen Baratheon','Stark','Tully',NULL,NULL,'Lannister',NULL,NULL,NULL,'win','ambush',1,1,1875,6000,'Robb Stark, Brynden Tully','Jaime Lannister',1,'Whispering Wood','The Riverlands',NULL);
INSERT INTO battles_data(name,year,battle_number,attacker_king,defender_king,attacker_1,attacker_2,attacker_3,attacker_4,defender_1,defender_2,defender_3,defender_4,attacker_outcome,battle_type,major_death,major_capture,attacker_size,defender_size,attacker_commander,defender_commander,summer,location,region,note) VALUES ('Battle of the Camps',298,6,'Robb Stark','Joffrey/Tommen Baratheon','Stark','Tully',NULL,NULL,'Lannister',NULL,NULL,NULL,'win','ambush',0,0,6000,12625,'Robb Stark, Tytos Blackwood, Brynden Tully','Lord Andros Brax, Forley Prester',1,'Riverrun','The Riverlands',NULL);
INSERT INTO battles_data(name,year,battle_number,attacker_king,defender_king,attacker_1,attacker_2,attacker_3,attacker_4,defender_1,defender_2,defender_3,defender_4,attacker_outcome,battle_type,major_death,major_capture,attacker_size,defender_size,attacker_commander,defender_commander,summer,location,region,note) VALUES ('Sack of Darry',298,7,'Joffrey/Tommen Baratheon','Robb Stark','Lannister',NULL,NULL,NULL,'Darry',NULL,NULL,NULL,'win','pitched battle',0,0,NULL,NULL,'Gregor Clegane','Lyman Darry',1,'Darry','The Riverlands',NULL);
INSERT INTO battles_data(name,year,battle_number,attacker_king,defender_king,attacker_1,attacker_2,attacker_3,attacker_4,defender_1,defender_2,defender_3,defender_4,attacker_outcome,battle_type,major_death,major_capture,attacker_size,defender_size,attacker_commander,defender_commander,summer,location,region,note) VALUES ('Battle of Moat Cailin',299,8,'Balon/Euron Greyjoy','Robb Stark','Greyjoy',NULL,NULL,NULL,'Stark',NULL,NULL,NULL,'win','pitched battle',0,0,NULL,NULL,'Victarion Greyjoy',NULL,1,'Moat Cailin','The North',NULL);
INSERT INTO battles_data(name,year,battle_number,attacker_king,defender_king,attacker_1,attacker_2,attacker_3,attacker_4,defender_1,defender_2,defender_3,defender_4,attacker_outcome,battle_type,major_death,major_capture,attacker_size,defender_size,attacker_commander,defender_commander,summer,location,region,note) VALUES ('Battle of Deepwood Motte',299,9,'Balon/Euron Greyjoy','Robb Stark','Greyjoy',NULL,NULL,NULL,'Stark',NULL,NULL,NULL,'win','siege',0,0,1000,NULL,'Asha Greyjoy',NULL,1,'Deepwood Motte','The North',NULL);
INSERT INTO battles_data(name,year,battle_number,attacker_king,defender_king,attacker_1,attacker_2,attacker_3,attacker_4,defender_1,defender_2,defender_3,defender_4,attacker_outcome,battle_type,major_death,major_capture,attacker_size,defender_size,attacker_commander,defender_commander,summer,location,region,note) VALUES ('Battle of the Stony Shore',299,10,'Balon/Euron Greyjoy','Robb Stark','Greyjoy',NULL,NULL,NULL,'Stark',NULL,NULL,NULL,'win','ambush',0,0,264,NULL,'Theon Greyjoy',NULL,1,'Stony Shore','The North','Greyjoy''s troop number based on the Battle of Deepwood Motte, in which Asha had 1000 soldier on 30 longships. That comes out to ~33 per longship. In the Battle of the Stony Shore, Theon has 8 longships, and just we can estimate that he has 8*33 =265 troops.');
INSERT INTO battles_data(name,year,battle_number,attacker_king,defender_king,attacker_1,attacker_2,attacker_3,attacker_4,defender_1,defender_2,defender_3,defender_4,attacker_outcome,battle_type,major_death,major_capture,attacker_size,defender_size,attacker_commander,defender_commander,summer,location,region,note) VALUES ('Battle of Torrhen''s Square',299,11,'Robb Stark','Balon/Euron Greyjoy','Stark',NULL,NULL,NULL,'Greyjoy',NULL,NULL,NULL,'win','pitched battle',0,0,244,900,'Rodrik Cassel, Cley Cerwyn','Dagmer Cleftjaw',1,'Torrhen''s Square','The North','Greyjoy''s troop number comes from the 264 estimate to have arrived on the stony shore minus the 20 Theon takes to attack Winterfell. Thus 264-20=244');
INSERT INTO battles_data(name,year,battle_number,attacker_king,defender_king,attacker_1,attacker_2,attacker_3,attacker_4,defender_1,defender_2,defender_3,defender_4,attacker_outcome,battle_type,major_death,major_capture,attacker_size,defender_size,attacker_commander,defender_commander,summer,location,region,note) VALUES ('Battle of Winterfell',299,12,'Balon/Euron Greyjoy','Robb Stark','Greyjoy',NULL,NULL,NULL,'Stark',NULL,NULL,NULL,'win','ambush',0,1,20,NULL,'Theon Greyjoy','Bran Stark',1,'Winterfell','The North','It isn''t mentioned how many Stark men are left in Winterfell, other than "very few".');
INSERT INTO battles_data(name,year,battle_number,attacker_king,defender_king,attacker_1,attacker_2,attacker_3,attacker_4,defender_1,defender_2,defender_3,defender_4,attacker_outcome,battle_type,major_death,major_capture,attacker_size,defender_size,attacker_commander,defender_commander,summer,location,region,note) VALUES ('Sack of Torrhen''s Square',299,13,'Balon/Euron Greyjoy','Balon/Euron Greyjoy','Greyjoy',NULL,NULL,NULL,'Stark',NULL,NULL,NULL,'win','siege',0,1,NULL,NULL,'Dagmer Cleftjaw',NULL,1,'Torrhen''s Square','The North',NULL);
INSERT INTO battles_data(name,year,battle_number,attacker_king,defender_king,attacker_1,attacker_2,attacker_3,attacker_4,defender_1,defender_2,defender_3,defender_4,attacker_outcome,battle_type,major_death,major_capture,attacker_size,defender_size,attacker_commander,defender_commander,summer,location,region,note) VALUES ('Sack of Winterfell',299,14,'Joffrey/Tommen Baratheon','Robb Stark','Bolton','Greyjoy',NULL,NULL,'Stark',NULL,NULL,NULL,'win','ambush',1,0,618,2000,'Ramsay Snow, Theon Greyjoy ','Rodrik Cassel, Cley Cerwyn, Leobald Tallhart',1,'Winterfell','The North','Since House Bolton betrays the Starks for House Lannister, we code this battle as between these two houses. Greyjoy men, numbering only 20, don''t play a major part in the fighting and end up dying anyway.');
INSERT INTO battles_data(name,year,battle_number,attacker_king,defender_king,attacker_1,attacker_2,attacker_3,attacker_4,defender_1,defender_2,defender_3,defender_4,attacker_outcome,battle_type,major_death,major_capture,attacker_size,defender_size,attacker_commander,defender_commander,summer,location,region,note) VALUES ('Battle of Oxcross',299,15,'Robb Stark','Joffrey/Tommen Baratheon','Stark','Tully',NULL,NULL,'Lannister',NULL,NULL,NULL,'win','ambush',1,1,6000,10000,'Robb Stark, Brynden Tully','Stafford Lannister, Roland Crakehall, Antario Jast',1,'Oxcross','The Westerlands',NULL);
INSERT INTO battles_data(name,year,battle_number,attacker_king,defender_king,attacker_1,attacker_2,attacker_3,attacker_4,defender_1,defender_2,defender_3,defender_4,attacker_outcome,battle_type,major_death,major_capture,attacker_size,defender_size,attacker_commander,defender_commander,summer,location,region,note) VALUES ('Siege of Storm''s End',299,16,'Stannis Baratheon','Renly Baratheon','Baratheon',NULL,NULL,NULL,'Baratheon',NULL,NULL,NULL,'win','siege',1,0,5000,20000,'Stannis Baratheon, Davos Seaworth','Renly Baratheon, Cortnay Penrose, Loras Tyrell, Randyll Tarly, Mathis Rowan',1,'Storm''s End','The Stormlands',NULL);
INSERT INTO battles_data(name,year,battle_number,attacker_king,defender_king,attacker_1,attacker_2,attacker_3,attacker_4,defender_1,defender_2,defender_3,defender_4,attacker_outcome,battle_type,major_death,major_capture,attacker_size,defender_size,attacker_commander,defender_commander,summer,location,region,note) VALUES ('Battle of the Fords',299,17,'Joffrey/Tommen Baratheon','Robb Stark','Lannister',NULL,NULL,NULL,'Tully',NULL,NULL,NULL,'loss','pitched battle',0,0,20000,10000,'Tywin Lannister, Flement Brax, Gregor Clegane, Addam Marbrand, Lyle Crakehall, Leo Lefford','Edmure Tully, Jason Mallister, Karyl Vance',1,'Red Fork','The Riverlands',NULL);
INSERT INTO battles_data(name,year,battle_number,attacker_king,defender_king,attacker_1,attacker_2,attacker_3,attacker_4,defender_1,defender_2,defender_3,defender_4,attacker_outcome,battle_type,major_death,major_capture,attacker_size,defender_size,attacker_commander,defender_commander,summer,location,region,note) VALUES ('Sack of Harrenhal',299,18,'Robb Stark','Joffrey/Tommen Baratheon','Stark',NULL,NULL,NULL,'Lannister',NULL,NULL,NULL,'win','ambush',1,0,100,100,'Roose Bolton, Vargo Hoat, Robett Glover','Amory Lorch',1,'Harrenhal','The Riverlands',NULL);
INSERT INTO battles_data(name,year,battle_number,attacker_king,defender_king,attacker_1,attacker_2,attacker_3,attacker_4,defender_1,defender_2,defender_3,defender_4,attacker_outcome,battle_type,major_death,major_capture,attacker_size,defender_size,attacker_commander,defender_commander,summer,location,region,note) VALUES ('Battle of the Crag',299,19,'Robb Stark','Joffrey/Tommen Baratheon','Stark',NULL,NULL,NULL,'Lannister',NULL,NULL,NULL,'win','ambush',0,0,6000,NULL,'Robb Stark, Smalljon Umber, Black Walder Frey','Rolph Spicer',1,'Crag','The Westerlands',NULL);
INSERT INTO battles_data(name,year,battle_number,attacker_king,defender_king,attacker_1,attacker_2,attacker_3,attacker_4,defender_1,defender_2,defender_3,defender_4,attacker_outcome,battle_type,major_death,major_capture,attacker_size,defender_size,attacker_commander,defender_commander,summer,location,region,note) VALUES ('Battle of the Blackwater',299,20,'Stannis Baratheon','Joffrey/Tommen Baratheon','Baratheon',NULL,NULL,NULL,'Lannister',NULL,NULL,NULL,'loss','pitched battle',1,1,21000,7250,'Stannis Baratheon, Imry Florent, Guyard Morrigen, Rolland Storm, Salladhor Saan, Davos Seaworth','Tyrion Lannister, Jacelyn Bywater, Sandor Clegane, Tywin Lannister, Garlan Tyrell, Mace Tyrell, Randyll Tarly',1,'King''s Landing','The Crownlands',NULL);
INSERT INTO battles_data(name,year,battle_number,attacker_king,defender_king,attacker_1,attacker_2,attacker_3,attacker_4,defender_1,defender_2,defender_3,defender_4,attacker_outcome,battle_type,major_death,major_capture,attacker_size,defender_size,attacker_commander,defender_commander,summer,location,region,note) VALUES ('Siege of Darry',299,21,'Robb Stark','Joffrey/Tommen Baratheon','Darry',NULL,NULL,NULL,'Lannister',NULL,NULL,NULL,'win','siege',0,0,NULL,NULL,'Helman Tallhart',NULL,1,'Darry','The Riverlands',NULL);
INSERT INTO battles_data(name,year,battle_number,attacker_king,defender_king,attacker_1,attacker_2,attacker_3,attacker_4,defender_1,defender_2,defender_3,defender_4,attacker_outcome,battle_type,major_death,major_capture,attacker_size,defender_size,attacker_commander,defender_commander,summer,location,region,note) VALUES ('Battle of Duskendale',299,22,'Robb Stark','Joffrey/Tommen Baratheon','Stark',NULL,NULL,NULL,'Lannister',NULL,NULL,NULL,'loss','pitched battle',1,0,3000,NULL,'Robertt Glover, Helman Tallhart','Randyll Tarly, Gregor Clegane',1,'Duskendale','The Crownlands',NULL);
INSERT INTO battles_data(name,year,battle_number,attacker_king,defender_king,attacker_1,attacker_2,attacker_3,attacker_4,defender_1,defender_2,defender_3,defender_4,attacker_outcome,battle_type,major_death,major_capture,attacker_size,defender_size,attacker_commander,defender_commander,summer,location,region,note) VALUES ('Battle of the Burning Septry',299,23,NULL,NULL,'Brotherhood without Banners',NULL,NULL,NULL,'Brave Companions',NULL,NULL,NULL,'win','pitched battle',0,0,NULL,NULL,NULL,NULL,1,NULL,'The Riverlands',NULL);
INSERT INTO battles_data(name,year,battle_number,attacker_king,defender_king,attacker_1,attacker_2,attacker_3,attacker_4,defender_1,defender_2,defender_3,defender_4,attacker_outcome,battle_type,major_death,major_capture,attacker_size,defender_size,attacker_commander,defender_commander,summer,location,region,note) VALUES ('Battle of the Ruby Ford',299,24,'Joffrey/Tommen Baratheon','Robb Stark','Lannister',NULL,NULL,NULL,'Stark',NULL,NULL,NULL,'win','pitched battle',0,0,NULL,6000,'Gregor Clegane','Roose Bolton, Wylis Manderly',NULL,'Ruby Ford','The Riverlands',NULL);
INSERT INTO battles_data(name,year,battle_number,attacker_king,defender_king,attacker_1,attacker_2,attacker_3,attacker_4,defender_1,defender_2,defender_3,defender_4,attacker_outcome,battle_type,major_death,major_capture,attacker_size,defender_size,attacker_commander,defender_commander,summer,location,region,note) VALUES ('Retaking of Harrenhal',299,25,'Joffrey/Tommen Baratheon',NULL,'Lannister',NULL,NULL,NULL,'Brave Companions',NULL,NULL,NULL,'win','pitched battle',1,0,NULL,NULL,'Gregor Clegane','Vargo Hoat',1,'Harrenhal','The Riverlands',NULL);
INSERT INTO battles_data(name,year,battle_number,attacker_king,defender_king,attacker_1,attacker_2,attacker_3,attacker_4,defender_1,defender_2,defender_3,defender_4,attacker_outcome,battle_type,major_death,major_capture,attacker_size,defender_size,attacker_commander,defender_commander,summer,location,region,note) VALUES ('The Red Wedding',299,26,'Joffrey/Tommen Baratheon','Robb Stark','Frey','Bolton',NULL,NULL,'Stark',NULL,NULL,NULL,'win','ambush',1,1,3500,3500,'Walder Frey, Roose Bolton, Walder Rivers','Robb Stark',1,'The Twins','The Riverlands','This observation refers to the battle against the Stark men, not the attack on the wedding');
INSERT INTO battles_data(name,year,battle_number,attacker_king,defender_king,attacker_1,attacker_2,attacker_3,attacker_4,defender_1,defender_2,defender_3,defender_4,attacker_outcome,battle_type,major_death,major_capture,attacker_size,defender_size,attacker_commander,defender_commander,summer,location,region,note) VALUES ('Siege of Seagard',299,27,'Robb Stark','Joffrey/Tommen Baratheon','Frey',NULL,NULL,NULL,'Mallister',NULL,NULL,NULL,'win','siege',0,1,NULL,NULL,'Walder Frey','Jason Mallister',1,'Seagard','The Riverlands',NULL);
INSERT INTO battles_data(name,year,battle_number,attacker_king,defender_king,attacker_1,attacker_2,attacker_3,attacker_4,defender_1,defender_2,defender_3,defender_4,attacker_outcome,battle_type,major_death,major_capture,attacker_size,defender_size,attacker_commander,defender_commander,summer,location,region,note) VALUES ('Battle of Castle Black',300,28,'Stannis Baratheon','Mance Rayder','Free folk','Thenns','Giants',NULL,'Night''s Watch','Baratheon',NULL,NULL,'loss','siege',1,1,100000,1240,'Mance Rayder, Tormund Giantsbane, Harma Dogshead, Magnar Styr, Varamyr','Stannis Baratheon, Jon Snow, Donal Noye, Cotter Pyke',0,'Castle Black','Beyond the Wall',NULL);
INSERT INTO battles_data(name,year,battle_number,attacker_king,defender_king,attacker_1,attacker_2,attacker_3,attacker_4,defender_1,defender_2,defender_3,defender_4,attacker_outcome,battle_type,major_death,major_capture,attacker_size,defender_size,attacker_commander,defender_commander,summer,location,region,note) VALUES ('Fall of Moat Cailin',300,29,'Joffrey/Tommen Baratheon','Balon/Euron Greyjoy','Bolton',NULL,NULL,NULL,'Greyjoy',NULL,NULL,NULL,'win','siege',0,0,NULL,NULL,'Ramsey Bolton',NULL,0,'Moat Cailin','The North',NULL);
INSERT INTO battles_data(name,year,battle_number,attacker_king,defender_king,attacker_1,attacker_2,attacker_3,attacker_4,defender_1,defender_2,defender_3,defender_4,attacker_outcome,battle_type,major_death,major_capture,attacker_size,defender_size,attacker_commander,defender_commander,summer,location,region,note) VALUES ('Sack of Saltpans',300,30,NULL,NULL,'Brave Companions',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'win','razing',0,0,NULL,NULL,'Rorge',NULL,0,'Saltpans','The Riverlands',NULL);
INSERT INTO battles_data(name,year,battle_number,attacker_king,defender_king,attacker_1,attacker_2,attacker_3,attacker_4,defender_1,defender_2,defender_3,defender_4,attacker_outcome,battle_type,major_death,major_capture,attacker_size,defender_size,attacker_commander,defender_commander,summer,location,region,note) VALUES ('Retaking of Deepwood Motte',300,31,'Stannis Baratheon','Balon/Euron Greyjoy','Baratheon','Karstark','Mormont','Glover','Greyjoy',NULL,NULL,NULL,'win','pitched battle',0,0,4500,200,'Stannis Baratheon, Alysane Mormot','Asha Greyjoy',0,'Deepwood Motte','The North',NULL);
INSERT INTO battles_data(name,year,battle_number,attacker_king,defender_king,attacker_1,attacker_2,attacker_3,attacker_4,defender_1,defender_2,defender_3,defender_4,attacker_outcome,battle_type,major_death,major_capture,attacker_size,defender_size,attacker_commander,defender_commander,summer,location,region,note) VALUES ('Battle of the Shield Islands',300,32,'Balon/Euron Greyjoy','Joffrey/Tommen Baratheon','Greyjoy',NULL,NULL,NULL,'Tyrell',NULL,NULL,NULL,'win','pitched battle',0,0,NULL,NULL,'Euron Greyjoy, Victarion Greyjoy',NULL,0,'Shield Islands','The Reach',NULL);
INSERT INTO battles_data(name,year,battle_number,attacker_king,defender_king,attacker_1,attacker_2,attacker_3,attacker_4,defender_1,defender_2,defender_3,defender_4,attacker_outcome,battle_type,major_death,major_capture,attacker_size,defender_size,attacker_commander,defender_commander,summer,location,region,note) VALUES ('Invasion of Ryamsport, Vinetown, and Starfish Harbor',300,33,'Balon/Euron Greyjoy','Joffrey/Tommen Baratheon','Greyjoy',NULL,NULL,NULL,'Tyrell',NULL,NULL,NULL,'win','razing',0,0,NULL,NULL,'Euron Greyjoy, Victarion Greyjoy',NULL,0,'Ryamsport, Vinetown, Starfish Harbor','The Reach',NULL);
INSERT INTO battles_data(name,year,battle_number,attacker_king,defender_king,attacker_1,attacker_2,attacker_3,attacker_4,defender_1,defender_2,defender_3,defender_4,attacker_outcome,battle_type,major_death,major_capture,attacker_size,defender_size,attacker_commander,defender_commander,summer,location,region,note) VALUES ('Second Seige of Storm''s End',300,34,'Joffrey/Tommen Baratheon','Stannis Baratheon','Baratheon',NULL,NULL,NULL,'Baratheon',NULL,NULL,NULL,'win','siege',0,0,NULL,200,'Mace Tyrell, Mathis Rowan','Gilbert Farring',0,'Storm''s End','The Stormlands',NULL);
INSERT INTO battles_data(name,year,battle_number,attacker_king,defender_king,attacker_1,attacker_2,attacker_3,attacker_4,defender_1,defender_2,defender_3,defender_4,attacker_outcome,battle_type,major_death,major_capture,attacker_size,defender_size,attacker_commander,defender_commander,summer,location,region,note) VALUES ('Siege of Dragonstone',300,35,'Joffrey/Tommen Baratheon','Stannis Baratheon','Baratheon',NULL,NULL,NULL,'Baratheon',NULL,NULL,NULL,'win','siege',0,0,2000,NULL,'Loras Tyrell, Raxter Redwyne','Rolland Storm',0,'Dragonstone','The Stormlands',NULL);
INSERT INTO battles_data(name,year,battle_number,attacker_king,defender_king,attacker_1,attacker_2,attacker_3,attacker_4,defender_1,defender_2,defender_3,defender_4,attacker_outcome,battle_type,major_death,major_capture,attacker_size,defender_size,attacker_commander,defender_commander,summer,location,region,note) VALUES ('Siege of Riverrun',300,36,'Joffrey/Tommen Baratheon','Robb Stark','Lannister','Frey',NULL,NULL,'Tully',NULL,NULL,NULL,'win','siege',0,0,3000,NULL,'Daven Lannister, Ryman Fey, Jaime Lannister','Brynden Tully',0,'Riverrun','The Riverlands',NULL);
INSERT INTO battles_data(name,year,battle_number,attacker_king,defender_king,attacker_1,attacker_2,attacker_3,attacker_4,defender_1,defender_2,defender_3,defender_4,attacker_outcome,battle_type,major_death,major_capture,attacker_size,defender_size,attacker_commander,defender_commander,summer,location,region,note) VALUES ('Siege of Raventree',300,37,'Joffrey/Tommen Baratheon','Robb Stark','Bracken','Lannister',NULL,NULL,'Blackwood',NULL,NULL,NULL,'win','siege',0,1,1500,NULL,'Jonos Bracken, Jaime Lannister','Tytos Blackwood',0,'Raventree','The Riverlands',NULL);
INSERT INTO battles_data(name,year,battle_number,attacker_king,defender_king,attacker_1,attacker_2,attacker_3,attacker_4,defender_1,defender_2,defender_3,defender_4,attacker_outcome,battle_type,major_death,major_capture,attacker_size,defender_size,attacker_commander,defender_commander,summer,location,region,note) VALUES ('Siege of Winterfell',300,38,'Stannis Baratheon','Joffrey/Tommen Baratheon','Baratheon','Karstark','Mormont','Glover','Bolton','Frey',NULL,NULL,NULL,NULL,NULL,NULL,5000,8000,'Stannis Baratheon','Roose Bolton',0,'Winterfell','The North',NULL);


select * from battles_data;
